# Cloudflare Workers configuration file
# This file configures your Cloudflare Worker for the contact form function

name = "portfolio-contact-form"
main = "functions/submit.js"
compatibility_date = "2024-01-01"

# Environment variables (uncomment and configure as needed)
# [env.production.vars]
# SENDGRID_API_KEY = "your-sendgrid-api-key"
# DATABASE_URL = "your-database-url"

# [env.staging.vars]
# SENDGRID_API_KEY = "your-staging-sendgrid-api-key"
# DATABASE_URL = "your-staging-database-url"

# Routes configuration
# Uncomment and modify the route pattern to match your domain
# routes = [
#   { pattern = "yourdomain.com/api/submit", custom_domain = true }
# ]

# KV Namespaces (if you need to store data)
# [[kv_namespaces]]
# binding = "CONTACT_SUBMISSIONS"
# id = "your-kv-namespace-id"

# D1 Database (if you need a database)
# [[d1_databases]]
# binding = "DB"
# database_name = "contact-form-db"
# database_id = "your-database-id"
